import { Card, SmallOrder } from './src/api/data-contracts';

export const cardsArray: Card[] = [
  {
    publishedAt: '',
    advertisementId: 1,
    imageUrl: 'http://dummyimage.com/286x282.png/cc0000/ffffff',
    title: 'There Be Dragons',
    price: 546,
    publishedBy: 1,
    publisherName: 'Wendy Mercy',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/cc0000/ffffff',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
  },
  {
    publishedAt: '',
    advertisementId: 2,
    imageUrl: 'http://dummyimage.com/286x282.png/5fa2dd/ffffff',
    title: 'Prometheus',
    price: 1196,
    publishedBy: 1,
    publisherName: 'Gardie Souch',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/ff4444/ffffff',
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
  },
  {
    publishedAt: '',
    advertisementId: 3,
    imageUrl: 'http://dummyimage.com/286x282.png/ff4444/ffffff',
    title: 'Adventures of Baron Munchausen, The',
    price: 521,
    publishedBy: 1,
    publisherName: 'Catha Beddis',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/cc0000/ffffff',
    description:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
  },
  {
    publishedAt: '',
    advertisementId: 4,
    imageUrl: 'http://dummyimage.com/286x282.png/cc0000/ffffff',
    title: 'Harry Potter and the Deathly Hallows: Part 1',
    price: 1337,
    publishedBy: 1,
    publisherName: 'Burch Sharphurst',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/ff4444/ffffff',
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
  },
  {
    publishedAt: '',
    advertisementId: 5,
    imageUrl: 'http://dummyimage.com/286x282.png/cc0000/ffffff',
    title: 'Force of Evil',
    price: 352,
    publishedBy: 1,
    publisherName: 'Derrek Artingstall',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/ff4444/ffffff',
    description:
      'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
  },
  {
    publishedAt: '',
    advertisementId: 6,
    imageUrl: 'http://dummyimage.com/286x282.png/cc0000/ffffff',
    title: 'Flight That Fought Back, The',
    price: 431,
    publishedBy: 1,
    publisherName: 'Ginger Erickssen',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/ff4444/ffffff',
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
  },
  {
    publishedAt: '',
    advertisementId: 7,
    imageUrl: 'http://dummyimage.com/286x282.png/dddddd/000000',
    title: 'Looking for Lenny ',
    price: 1812,
    publishedBy: 1,
    publisherName: 'Georgeanne Shead',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/ff4444/ffffff',
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
  },
  {
    publishedAt: '',
    advertisementId: 8,
    imageUrl: 'http://dummyimage.com/286x282.png/ff4444/ffffff',
    title:
      'Year My Parents Went on Vacation, The (O Ano em Que Meus Pais Saíram de Férias)',
    price: 1648,
    publishedBy: 1,
    publisherName: 'Sherilyn Vasin',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/5fa2dd/ffffff',
    description: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.',
  },
  {
    publishedAt: '',
    advertisementId: 9,
    imageUrl: 'http://dummyimage.com/286x282.png/ff4444/ffffff',
    title: 'Machine, The',
    price: 792,
    publishedBy: 1,
    publisherName: 'Mellicent Fuentes',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/ff4444/ffffff',
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
  },
  {
    publishedAt: '',
    advertisementId: 10,
    publishedBy: 1,
    imageUrl: 'http://dummyimage.com/286x282.png/cc0000/ffffff',
    title: 'Angela',
    price: 1855,
    publisherName: 'Kinnie Lillyman',
    publisherAvatarUrl: 'http://dummyimage.com/30x30.png/cc0000/ffffff',
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
  },
];

export const adsRowMock = [
  {
    productId: 1,
    title: 'Research Associate',
    type: 'equipment',
    description:
      'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
  },
  {
    productId: 2,
    title: 'Nuclear Power Engineer',
    type: 'service',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
  },
  {
    productId: 3,
    title: 'Developer II',
    type: 'equipment',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
  },
  {
    productId: 4,
    title: 'Web Developer II',
    type: 'service',
    description: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
  },
  {
    productId: 5,
    title: 'Accounting Assistant IV',
    type: 'service',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
  },
  {
    productId: 6,
    title: 'Teacher',
    type: 'equipment',
    description:
      'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
  },
  {
    productId: 7,
    title: 'Marketing Manager',
    type: 'equipment',
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
  },
  {
    productId: 8,
    title: 'Safety Technician II',
    type: 'equipment',
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
  },
  {
    productId: 9,
    title: 'Chief Design Engineer',
    type: 'service',
    description: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
  },
  {
    productId: 10,
    title: 'Physical Therapy Assistant',
    type: 'service',
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
  },
  {
    productId: 11,
    title: 'Web Designer IV',
    type: 'service',
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
  },
  {
    productId: 12,
    title: 'Compensation Analyst',
    type: 'equipment',
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
  },
  {
    productId: 13,
    title: 'VP Sales',
    type: 'equipment',
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
  },
  {
    productId: 14,
    title: 'VP Product Management',
    type: 'equipment',
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
  },
  {
    productId: 15,
    title: 'Web Developer III',
    type: 'service',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
  },
];

export const tableData: SmallOrder[] = [
  {
    orderId: 1,
    title: 'Voyatouch',
    price: 7580,
    acceptedAt: '2024-02-11',
    deadlineAt: '2023-06-29',
    completedAt: '2023-06-17',
    status: 'ARRIVED',
  },
  {
    orderId: 2,
    title: 'Home Ing',
    price: 7898,
    acceptedAt: '2024-02-20',
    deadlineAt: '2024-03-15',
    completedAt: '2023-03-06',
    status: 'ARRIVED',
  },
  {
    orderId: 3,
    title: 'Cardguard',
    price: 8439,
    acceptedAt: '2023-11-16',
    deadlineAt: '2023-09-13',
    completedAt: '2023-07-02',
    status: 'PENDING',
  },
  {
    orderId: 4,
    title: 'Y-find',
    price: 8410,
    acceptedAt: '2023-10-01',
    deadlineAt: '2024-02-27',
    completedAt: '2023-05-05',
    status: 'DISPATCHED',
  },
  {
    orderId: 5,
    title: 'Tres-Zap',
    price: 6791,
    acceptedAt: '2023-12-05',
    deadlineAt: '2024-03-07',
    completedAt: '2024-03-02',
    status: 'PENDING',
  },
  {
    orderId: 6,
    title: 'Fintone',
    price: 5204,
    acceptedAt: '2023-09-12',
    deadlineAt: '2023-09-20',
    completedAt: '2023-08-09',
    status: 'CANCELED',
  },
  {
    orderId: 7,
    title: 'Matsoft',
    price: 9607,
    acceptedAt: '2024-01-07',
    deadlineAt: '2023-07-03',
    completedAt: '2023-07-26',
    status: 'IN_PROGRESS',
  },
  {
    orderId: 8,
    title: 'Latlux',
    price: 3455,
    acceptedAt: '2023-12-11',
    deadlineAt: '2023-03-02',
    completedAt: '2023-12-14',
    status: 'CANCELED',
  },
  {
    orderId: 9,
    title: 'Greenlam',
    price: 9862,
    acceptedAt: '2024-03-09',
    deadlineAt: '2024-02-03',
    completedAt: '2023-06-16',
    status: 'CHECKING',
  },
  {
    orderId: 10,
    title: 'Zoolab',
    price: 3076,
    acceptedAt: '2023-12-18',
    deadlineAt: '2024-02-25',
    completedAt: '2023-09-04',
    status: 'IN_PROGRESS',
  },
  {
    orderId: 11,
    title: 'Holdlamis',
    price: 1492,
    acceptedAt: '2023-07-12',
    deadlineAt: '2023-08-10',
    completedAt: '2023-11-01',
    status: 'ARRIVED',
  },
  {
    orderId: 12,
    title: 'Tampflex',
    price: 6626,
    acceptedAt: '2023-09-02',
    deadlineAt: '2023-06-29',
    completedAt: '2023-09-18',
    status: 'CHECKING',
  },
  {
    orderId: 13,
    title: 'Latlux',
    price: 3848,
    acceptedAt: '2023-04-11',
    deadlineAt: '2023-11-05',
    completedAt: '2024-04-13',
    status: 'ARRIVED',
  },
  {
    orderId: 14,
    title: 'Cookley',
    price: 2635,
    acceptedAt: '2023-05-31',
    deadlineAt: '2023-07-17',
    completedAt: '2023-09-27',
    status: 'DISPATCHED',
  },
  {
    orderId: 15,
    title: 'Cardify',
    price: 7754,
    acceptedAt: '2024-03-10',
    deadlineAt: '2023-06-28',
    completedAt: '2023-10-26',
    status: 'ARRIVED',
  },
  {
    orderId: 16,
    title: 'Bytecard',
    price: 2744,
    acceptedAt: '2023-07-08',
    deadlineAt: '2024-01-13',
    completedAt: '2023-03-21',
    status: 'PENDING',
  },
  {
    orderId: 17,
    title: 'Viva',
    price: 2430,
    acceptedAt: '2024-04-03',
    deadlineAt: '2023-04-06',
    completedAt: '2023-06-08',
    status: 'ARRIVED',
  },
  {
    orderId: 18,
    title: 'Pannier',
    price: 4665,
    acceptedAt: '2023-08-06',
    deadlineAt: '2023-12-10',
    completedAt: '2023-10-15',
    status: 'IN_PROGRESS',
  },
  {
    orderId: 19,
    title: 'Alpha',
    price: 7190,
    acceptedAt: '2023-07-19',
    deadlineAt: '2023-04-01',
    completedAt: '2023-11-20',
    status: 'COMPLETED',
  },
  {
    orderId: 20,
    title: 'Fintone',
    price: 6147,
    acceptedAt: '2023-03-13',
    deadlineAt: '2023-12-09',
    completedAt: '2023-06-02',
    status: 'ARRIVED',
  },
];
