import { OrderSummary } from './src/api/data-contracts';

export const MOCK_DATA: OrderSummary[] = [
  {
    orderId: 56,
    key: 'Ara',
    title: 'Worboy',
    description: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    price: 319097,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'PENDING',
    acceptedAt: '2024-03-29',
    deadlineAt: '2023-06-29',
    completedAt: '2024-04-23',
  },
  {
    orderId: 89,
    key: 'Linnea',
    title: 'Boumphrey',
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    price: 583578,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'NEW',
    acceptedAt: '2024-01-28',
    deadlineAt: '2023-08-22',
    completedAt: '2023-12-19',
  },
  {
    orderId: 15,
    key: 'Basia',
    title: 'Coverly',
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    price: 430774,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-06-02',
    deadlineAt: '2023-09-08',
    completedAt: '2023-07-17',
  },
  {
    orderId: 69,
    key: 'Amos',
    title: 'Grogor',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    price: 518537,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-11-25',
    deadlineAt: '2024-01-19',
    completedAt: '2024-04-14',
  },
  {
    orderId: 96,
    key: 'Andie',
    title: 'Wadman',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    price: 961032,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-12-17',
    deadlineAt: '2023-06-24',
    completedAt: '2023-11-27',
  },
  {
    orderId: 67,
    key: 'Eda',
    title: 'Ladd',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    price: 47687,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-09-05',
    deadlineAt: '2023-11-28',
    completedAt: '2024-01-19',
  },
  {
    orderId: 65,
    key: 'Clint',
    title: 'Conrard',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    price: 618939,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2023-10-31',
    deadlineAt: '2023-12-26',
    completedAt: '2023-11-15',
  },
  {
    orderId: 50,
    key: 'Laetitia',
    title: 'Ewing',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    price: 87093,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CANCELED',
    acceptedAt: '2023-10-15',
    deadlineAt: '2024-03-07',
    completedAt: '2023-11-02',
  },
  {
    orderId: 45,
    key: 'Lilah',
    title: 'Doleman',
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    price: 744615,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2023-07-12',
    deadlineAt: '2024-04-22',
    completedAt: '2023-06-08',
  },
  {
    orderId: 94,
    key: 'Tabby',
    title: 'Snowman',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    price: 408925,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'NEW',
    acceptedAt: '2023-12-10',
    deadlineAt: '2023-10-18',
    completedAt: '2024-01-07',
  },
  {
    orderId: 63,
    key: 'Caye',
    title: 'Duddy',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    price: 887783,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-06-07',
    deadlineAt: '2023-06-23',
    completedAt: '2024-04-11',
  },
  {
    orderId: 86,
    key: 'Pammy',
    title: 'Soldner',
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    price: 425618,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-09-15',
    deadlineAt: '2023-08-21',
    completedAt: '2024-02-08',
  },
  {
    orderId: 36,
    key: 'Bartholomew',
    title: 'Ceaplen',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    price: 290123,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-10-26',
    deadlineAt: '2024-04-27',
    completedAt: '2023-12-18',
  },
  {
    orderId: 77,
    key: 'Kerstin',
    title: 'Tebbut',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    price: 641061,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2024-04-10',
    deadlineAt: '2023-11-24',
    completedAt: '2023-05-24',
  },
  {
    orderId: 70,
    key: 'Catherine',
    title: 'Burkhill',
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    price: 224268,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2023-08-03',
    deadlineAt: '2023-05-30',
    completedAt: '2023-11-13',
  },
  {
    orderId: 26,
    key: 'Genna',
    title: 'Loncaster',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    price: 577107,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'CANCELED',
    acceptedAt: '2024-01-07',
    deadlineAt: '2023-07-15',
    completedAt: '2023-11-05',
  },
  {
    orderId: 93,
    key: 'Luisa',
    title: 'Tooze',
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    price: 199133,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'PENDING',
    acceptedAt: '2023-10-07',
    deadlineAt: '2024-01-14',
    completedAt: '2024-04-13',
  },
  {
    orderId: 15,
    key: 'Tonnie',
    title: 'Caird',
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    price: 591006,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'NEW',
    acceptedAt: '2023-10-06',
    deadlineAt: '2023-12-26',
    completedAt: '2023-07-16',
  },
  {
    orderId: 6,
    key: 'Kissiah',
    title: 'Melato',
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    price: 116632,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-10-14',
    deadlineAt: '2023-12-03',
    completedAt: '2023-08-16',
  },
  {
    orderId: 79,
    key: 'Mort',
    title: 'McKleod',
    description:
      'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    price: 493974,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CHECKING',
    acceptedAt: '2024-05-17',
    deadlineAt: '2023-06-05',
    completedAt: '2023-07-01',
  },
  {
    orderId: 79,
    key: 'Davide',
    title: 'Prinne',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    price: 825,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-08-14',
    deadlineAt: '2024-04-03',
    completedAt: '2024-03-24',
  },
  {
    orderId: 40,
    key: 'Casar',
    title: 'Beaney',
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    price: 840221,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-11-28',
    deadlineAt: '2023-05-19',
    completedAt: '2023-11-24',
  },
  {
    orderId: 92,
    key: 'Arleen',
    title: 'Mayhead',
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    price: 149664,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2023-07-11',
    deadlineAt: '2023-09-28',
    completedAt: '2023-12-21',
  },
  {
    orderId: 62,
    key: 'Flory',
    title: 'Rubbert',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    price: 553151,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CANCELED',
    acceptedAt: '2023-11-28',
    deadlineAt: '2023-06-22',
    completedAt: '2024-01-22',
  },
  {
    orderId: 22,
    key: 'Berti',
    title: 'Avory',
    description:
      'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    price: 750295,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2024-02-22',
    deadlineAt: '2023-07-15',
    completedAt: '2023-09-26',
  },
  {
    orderId: 58,
    key: 'Roxane',
    title: 'Durran',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    price: 827939,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'NEW',
    acceptedAt: '2024-03-21',
    deadlineAt: '2023-11-26',
    completedAt: '2023-10-21',
  },
  {
    orderId: 84,
    key: 'Alvie',
    title: 'Cullen',
    description:
      'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
    price: 432741,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-07-20',
    deadlineAt: '2023-11-12',
    completedAt: '2023-10-11',
  },
  {
    orderId: 7,
    key: 'Papageno',
    title: 'Mussen',
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    price: 467843,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-08-25',
    deadlineAt: '2023-12-29',
    completedAt: '2023-07-31',
  },
  {
    orderId: 27,
    key: 'Galina',
    title: 'Castagnone',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    price: 716454,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-08-18',
    deadlineAt: '2023-10-14',
    completedAt: '2023-10-19',
  },
  {
    orderId: 29,
    key: 'Desi',
    title: 'Stainburn',
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    price: 239220,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'ARRIVED',
    acceptedAt: '2023-10-21',
    deadlineAt: '2023-11-27',
    completedAt: '2023-10-09',
  },
  {
    orderId: 71,
    key: 'Calv',
    title: 'Laidlaw',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    price: 344226,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2024-04-08',
    deadlineAt: '2023-12-16',
    completedAt: '2023-12-03',
  },
  {
    orderId: 22,
    key: 'Tanner',
    title: 'Devenish',
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    price: 946968,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CANCELED',
    acceptedAt: '2024-02-25',
    deadlineAt: '2023-11-17',
    completedAt: '2024-04-11',
  },
  {
    orderId: 48,
    key: 'Dixie',
    title: 'Surgison',
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    price: 457428,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2024-03-12',
    deadlineAt: '2023-10-09',
    completedAt: '2023-11-25',
  },
  {
    orderId: 69,
    key: 'Kasper',
    title: 'Rodder',
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    price: 785075,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'NEW',
    acceptedAt: '2024-04-30',
    deadlineAt: '2023-07-06',
    completedAt: '2023-06-23',
  },
  {
    orderId: 68,
    key: 'Edith',
    title: 'Hands',
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    price: 105897,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-11-26',
    deadlineAt: '2024-04-03',
    completedAt: '2024-03-03',
  },
  {
    orderId: 77,
    key: 'Miguela',
    title: 'Mabe',
    description:
      'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    price: 875499,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-11-13',
    deadlineAt: '2023-10-05',
    completedAt: '2023-12-30',
  },
  {
    orderId: 72,
    key: 'Kimbra',
    title: 'Rebillard',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    price: 310514,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'DISPATCHED',
    acceptedAt: '2024-04-23',
    deadlineAt: '2023-10-01',
    completedAt: '2023-06-13',
  },
  {
    orderId: 57,
    key: 'Marney',
    title: 'Skarr',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    price: 323791,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2024-02-12',
    deadlineAt: '2023-09-20',
    completedAt: '2023-06-10',
  },
  {
    orderId: 26,
    key: 'Hallsy',
    title: 'Pray',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    price: 782005,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2023-08-05',
    deadlineAt: '2023-09-15',
    completedAt: '2024-04-01',
  },
  {
    orderId: 76,
    key: 'Katharyn',
    title: 'Houten',
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    price: 101330,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CANCELED',
    acceptedAt: '2024-01-14',
    deadlineAt: '2023-07-08',
    completedAt: '2024-02-19',
  },
  {
    orderId: 94,
    key: 'Modesta',
    title: 'Mangon',
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
    price: 937369,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'PENDING',
    acceptedAt: '2024-04-08',
    deadlineAt: '2023-08-11',
    completedAt: '2023-05-26',
  },
  {
    orderId: 91,
    key: 'Niels',
    title: 'Fritschel',
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    price: 763473,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'NEW',
    acceptedAt: '2023-10-10',
    deadlineAt: '2023-06-23',
    completedAt: '2023-12-15',
  },
  {
    orderId: 66,
    key: 'Alasdair',
    title: 'Stollery',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    price: 728417,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-12-26',
    deadlineAt: '2024-02-23',
    completedAt: '2023-11-24',
  },
  {
    orderId: 53,
    key: 'Ricoriki',
    title: 'Parslow',
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    price: 231349,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-05-19',
    deadlineAt: '2023-08-31',
    completedAt: '2023-07-03',
  },
  {
    orderId: 89,
    key: 'Patty',
    title: 'Benkhe',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    price: 928031,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2024-04-25',
    deadlineAt: '2023-05-21',
    completedAt: '2023-11-11',
  },
  {
    orderId: 30,
    key: 'Jori',
    title: 'Filppetti',
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    price: 45018,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-05-20',
    deadlineAt: '2024-03-08',
    completedAt: '2024-03-27',
  },
  {
    orderId: 78,
    key: 'Suzanna',
    title: 'Willerstone',
    description:
      'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    price: 159496,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2024-01-18',
    deadlineAt: '2023-08-19',
    completedAt: '2023-12-14',
  },
  {
    orderId: 57,
    key: 'Morganne',
    title: 'Petrowsky',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    price: 243493,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CANCELED',
    acceptedAt: '2023-06-06',
    deadlineAt: '2024-03-09',
    completedAt: '2024-02-27',
  },
  {
    orderId: 100,
    key: 'Bearnard',
    title: 'Dorbin',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    price: 653438,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2023-08-12',
    deadlineAt: '2023-10-22',
    completedAt: '2024-04-03',
  },
  {
    orderId: 51,
    key: 'Evaleen',
    title: 'Pandya',
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    price: 765248,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'NEW',
    acceptedAt: '2023-10-01',
    deadlineAt: '2024-04-19',
    completedAt: '2023-12-23',
  },
  {
    orderId: 77,
    key: 'Zebulen',
    title: 'Pennazzi',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    price: 117205,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-11-16',
    deadlineAt: '2023-12-28',
    completedAt: '2023-10-03',
  },
  {
    orderId: 95,
    key: 'Iormina',
    title: 'Davidzon',
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    price: 161359,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CHECKING',
    acceptedAt: '2024-03-27',
    deadlineAt: '2024-02-01',
    completedAt: '2024-02-22',
  },
  {
    orderId: 96,
    key: 'Rickey',
    title: 'Lusty',
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    price: 653353,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-07-11',
    deadlineAt: '2023-12-22',
    completedAt: '2024-02-22',
  },
  {
    orderId: 37,
    key: 'Ketti',
    title: 'Condliffe',
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    price: 810553,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-12-25',
    deadlineAt: '2024-02-22',
    completedAt: '2023-12-27',
  },
  {
    orderId: 37,
    key: 'Kerry',
    title: 'Antonacci',
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    price: 330608,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2024-01-12',
    deadlineAt: '2023-12-18',
    completedAt: '2024-04-09',
  },
  {
    orderId: 54,
    key: 'Angus',
    title: 'Bestar',
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    price: 44997,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'CANCELED',
    acceptedAt: '2024-02-28',
    deadlineAt: '2024-04-14',
    completedAt: '2024-02-02',
  },
  {
    orderId: 59,
    key: 'Petronilla',
    title: 'Dockwra',
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    price: 725763,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'PENDING',
    acceptedAt: '2023-05-27',
    deadlineAt: '2023-11-19',
    completedAt: '2024-04-10',
  },
  {
    orderId: 45,
    key: 'Ardyce',
    title: 'Samwyse',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    price: 263890,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'NEW',
    acceptedAt: '2023-08-16',
    deadlineAt: '2024-03-01',
    completedAt: '2024-04-04',
  },
  {
    orderId: 89,
    key: 'Moria',
    title: 'Primarolo',
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    price: 973614,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-09-19',
    deadlineAt: '2024-01-21',
    completedAt: '2024-02-06',
  },
  {
    orderId: 9,
    key: 'Adan',
    title: 'Filipczynski',
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    price: 704115,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-11-14',
    deadlineAt: '2023-12-14',
    completedAt: '2023-12-22',
  },
  {
    orderId: 45,
    key: 'Joe',
    title: 'Inkpen',
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    price: 404756,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2024-04-16',
    deadlineAt: '2023-09-29',
    completedAt: '2023-11-19',
  },
  {
    orderId: 11,
    key: 'Danyette',
    title: 'Beese',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    price: 24193,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-06-12',
    deadlineAt: '2023-08-29',
    completedAt: '2024-05-12',
  },
  {
    orderId: 87,
    key: 'Danila',
    title: 'Holwell',
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    price: 471481,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2024-03-27',
    deadlineAt: '2024-03-09',
    completedAt: '2023-07-20',
  },
  {
    orderId: 32,
    key: 'Janie',
    title: 'Feldmus',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    price: 188208,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2024-03-01',
    deadlineAt: '2023-11-27',
    completedAt: '2024-04-27',
  },
  {
    orderId: 59,
    key: 'Juline',
    title: 'Cardis',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.',
    price: 63587,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'NEW',
    acceptedAt: '2023-08-02',
    deadlineAt: '2024-05-11',
    completedAt: '2024-02-08',
  },
  {
    orderId: 6,
    key: 'Wallis',
    title: 'Wolvey',
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.',
    price: 340572,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2024-04-11',
    deadlineAt: '2023-08-05',
    completedAt: '2023-07-09',
  },
  {
    orderId: 71,
    key: 'Dorise',
    title: 'McKelvey',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    price: 751812,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-06-14',
    deadlineAt: '2023-05-27',
    completedAt: '2023-06-08',
  },
  {
    orderId: 47,
    key: 'Mickie',
    title: 'Maudlen',
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    price: 433801,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-11-03',
    deadlineAt: '2023-10-03',
    completedAt: '2024-04-30',
  },
  {
    orderId: 49,
    key: 'Sammy',
    title: 'Scantleberry',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    price: 240360,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2024-03-04',
    deadlineAt: '2023-10-07',
    completedAt: '2023-06-24',
  },
  {
    orderId: 18,
    key: 'Christian',
    title: 'Lamblot',
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    price: 691051,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2023-06-21',
    deadlineAt: '2023-05-27',
    completedAt: '2024-02-25',
  },
  {
    orderId: 91,
    key: 'Hasty',
    title: 'Barensen',
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    price: 86865,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'CANCELED',
    acceptedAt: '2023-12-01',
    deadlineAt: '2024-03-16',
    completedAt: '2023-09-20',
  },
  {
    orderId: 27,
    key: 'Rivi',
    title: 'Couthard',
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    price: 151340,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2023-08-19',
    deadlineAt: '2023-12-14',
    completedAt: '2024-02-23',
  },
  {
    orderId: 59,
    key: 'Eba',
    title: 'McLanaghan',
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    price: 799362,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'NEW',
    acceptedAt: '2024-01-24',
    deadlineAt: '2023-08-31',
    completedAt: '2023-05-28',
  },
  {
    orderId: 83,
    key: 'Vinni',
    title: 'Conduit',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    price: 576113,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'IN_PROGRESS',
    acceptedAt: '2024-01-30',
    deadlineAt: '2023-06-24',
    completedAt: '2023-12-15',
  },
  {
    orderId: 5,
    key: 'Mariya',
    title: 'Buchan',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    price: 333547,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-11-20',
    deadlineAt: '2024-03-25',
    completedAt: '2023-08-17',
  },
  {
    orderId: 4,
    key: 'Spense',
    title: 'Rzehorz',
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    price: 997503,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'DISPATCHED',
    acceptedAt: '2024-03-09',
    deadlineAt: '2023-11-24',
    completedAt: '2023-05-26',
  },
  {
    orderId: 67,
    key: 'Glenn',
    title: 'Henden',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    price: 540689,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-08-25',
    deadlineAt: '2024-03-10',
    completedAt: '2023-07-03',
  },
  {
    orderId: 26,
    key: 'Casey',
    title: 'Goadsby',
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    price: 131635,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2023-06-06',
    deadlineAt: '2024-05-03',
    completedAt: '2023-09-16',
  },
  {
    orderId: 57,
    key: 'Nelson',
    title: 'Waulker',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    price: 165714,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CANCELED',
    acceptedAt: '2023-10-04',
    deadlineAt: '2023-06-01',
    completedAt: '2023-12-03',
  },
  {
    orderId: 48,
    key: 'Denys',
    title: 'Ivanovic',
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    price: 317310,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'PENDING',
    acceptedAt: '2024-05-09',
    deadlineAt: '2024-04-20',
    completedAt: '2024-01-04',
  },
  {
    orderId: 63,
    key: 'Ashien',
    title: 'Gobbet',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    price: 20696,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'NEW',
    acceptedAt: '2023-10-04',
    deadlineAt: '2023-06-02',
    completedAt: '2023-07-06',
  },
  {
    orderId: 61,
    key: 'Axel',
    title: 'Clarage',
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    price: 924618,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'IN_PROGRESS',
    acceptedAt: '2024-01-28',
    deadlineAt: '2023-09-10',
    completedAt: '2023-06-04',
  },
  {
    orderId: 36,
    key: 'Padgett',
    title: 'Quinnell',
    description:
      'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    price: 668212,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'CHECKING',
    acceptedAt: '2023-12-22',
    deadlineAt: '2024-02-10',
    completedAt: '2024-04-25',
  },
  {
    orderId: 8,
    key: 'Daron',
    title: 'Chillistone',
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    price: 469783,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'DISPATCHED',
    acceptedAt: '2024-03-24',
    deadlineAt: '2023-06-06',
    completedAt: '2023-10-02',
  },
  {
    orderId: 25,
    key: 'Venus',
    title: 'Audry',
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    price: 702820,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'ARRIVED',
    acceptedAt: '2023-11-25',
    deadlineAt: '2023-11-07',
    completedAt: '2023-07-02',
  },
  {
    orderId: 75,
    key: 'Man',
    title: 'Naisbit',
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    price: 378731,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2024-02-20',
    deadlineAt: '2024-02-07',
    completedAt: '2023-06-13',
  },
  {
    orderId: 51,
    key: 'Valentin',
    title: 'Scowcroft',
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    price: 779368,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'CANCELED',
    acceptedAt: '2023-08-20',
    deadlineAt: '2023-08-21',
    completedAt: '2023-06-06',
  },
  {
    orderId: 23,
    key: 'Arri',
    title: 'Winspare',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    price: 68698,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2023-11-10',
    deadlineAt: '2024-04-12',
    completedAt: '2023-11-15',
  },
  {
    orderId: 21,
    key: 'Colan',
    title: 'Boorne',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    price: 675907,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'NEW',
    acceptedAt: '2024-01-31',
    deadlineAt: '2023-05-27',
    completedAt: '2023-07-18',
  },
  {
    orderId: 38,
    key: 'Verena',
    title: 'Saggers',
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    price: 321909,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-07-05',
    deadlineAt: '2023-06-16',
    completedAt: '2023-06-06',
  },
  {
    orderId: 18,
    key: 'Auguste',
    title: 'Scouler',
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    price: 751626,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'CHECKING',
    acceptedAt: '2024-01-29',
    deadlineAt: '2023-10-30',
    completedAt: '2023-09-23',
  },
  {
    orderId: 4,
    key: 'Elyssa',
    title: 'Kinnock',
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    price: 569009,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-11-11',
    deadlineAt: '2024-01-15',
    completedAt: '2023-06-23',
  },
  {
    orderId: 15,
    key: 'Sullivan',
    title: 'Brinicombe',
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    price: 439142,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'ARRIVED',
    acceptedAt: '2024-04-12',
    deadlineAt: '2023-09-27',
    completedAt: '2023-07-16',
  },
  {
    orderId: 3,
    key: 'Kimberly',
    title: 'Tottman',
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    price: 550872,
    imageUrl: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    status: 'COMPLETED',
    acceptedAt: '2024-02-14',
    deadlineAt: '2023-10-24',
    completedAt: '2023-11-26',
  },
  {
    orderId: 82,
    key: 'Kimmie',
    title: 'Huddart',
    description:
      'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
    price: 90263,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'CANCELED',
    acceptedAt: '2023-12-02',
    deadlineAt: '2024-02-01',
    completedAt: '2024-04-03',
  },
  {
    orderId: 89,
    key: 'Leo',
    title: 'Skacel',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    price: 510302,
    imageUrl: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    status: 'PENDING',
    acceptedAt: '2023-11-28',
    deadlineAt: '2023-10-22',
    completedAt: '2023-07-19',
  },
  {
    orderId: 35,
    key: 'Trisha',
    title: 'Mathews',
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    price: 543231,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'NEW',
    acceptedAt: '2024-01-22',
    deadlineAt: '2023-12-02',
    completedAt: '2023-09-15',
  },
  {
    orderId: 23,
    key: 'Aloysia',
    title: 'Do',
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    price: 954387,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'IN_PROGRESS',
    acceptedAt: '2023-10-23',
    deadlineAt: '2023-09-22',
    completedAt: '2024-04-03',
  },
  {
    orderId: 38,
    key: 'Cullan',
    title: 'Sandeson',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    price: 323220,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    status: 'CHECKING',
    acceptedAt: '2024-02-07',
    deadlineAt: '2023-09-21',
    completedAt: '2023-07-02',
  },
  {
    orderId: 85,
    key: 'Erhard',
    title: 'Cholonin',
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    price: 127010,
    imageUrl: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    status: 'DISPATCHED',
    acceptedAt: '2023-09-24',
    deadlineAt: '2023-11-09',
    completedAt: '2023-09-29',
  },
];
